-- Mock Data for clients table
INSERT INTO clients (
  slug, business_name, business_type, theme, whatsapp_number, whatsapp_message,
  hero_title, hero_lead, primary_cta, secondary_cta, accent_label, hero_asset_url,
  products_title, products, highlights, stats, proof_title, proof_items,
  testimonial_quote, testimonial_person, final_title, meta_title, meta_description
) VALUES
(
  'dapur-rendang-riau',
  'Dapur Rendang Riau',
  'Kuliner rumahan premium',
  'rendang',
  '6282387025429',
  'Halo Dapur Rendang Riau, saya ingin pesan paket rendang untuk acara/kantor.',
  'Rendang Riau pekat rempah, siap antar untuk makan kantor dan hampers keluarga.',
  'Landing page ini dibuat untuk membuat calon pembeli langsung paham menu andalan, paket kantor, bukti rasa, dan cara pesan tanpa perlu bolak-balik chat.',
  'Pesan Rendang',
  'Lihat Paket',
  'Masak harian terbatas',
  '/demo/dapur-rendang-riau.svg',
  'Menu yang paling mudah dijual dari halaman pertama.',
  '[{"name": "Nasi Box Rendang", "price": "Mulai Rp32rb", "desc": "Rendang sapi, nasi hangat, sambal ijo, sayur singkong, dan kerupuk."}, {"name": "Hampers Rendang", "price": "Mulai Rp185rb", "desc": "Kemasan premium untuk keluarga, kolega, dan hadiah hari besar."}, {"name": "Rendang 500gr", "price": "Rp155rb", "desc": "Rendang kering tahan simpan dengan rasa pedas gurih khas Riau."}]',
  '["Rendang sapi rempah kering", "Paket nasi box kantor", "Hampers rendang vakum"]',
  '[{"value": "4.9/5", "label": "rating pelanggan"}, {"value": "3 paket", "label": "nasi box & hampers"}, {"value": "H-1", "label": "pre-order aman"}]',
  'Rasa dulu, baru transaksi.',
  '["Foto menu besar sebagai bukti visual utama.", "Testimoni singkat untuk mengurangi ragu pembeli baru.", "CTA WhatsApp yang langsung membawa konteks pesanan."]',
  'Biasanya order lewat chat berantakan. Dengan halaman ini tim kantor tinggal pilih paket dan kirim jumlah box.',
  'Mira, admin kantor Sudirman',
  'Buat pembeli lapar sebelum chat pertama.',
  'Demo Landing Page Dapur Rendang Riau | PekanWeb Studio',
  'Contoh landing page satu halaman untuk brand rendang rumahan premium di Pekanbaru.'
),
(
  'loka-batik-pekanbaru',
  'Loka Batik Pekanbaru',
  'Fashion & retail',
  'batik',
  '6282387025429',
  'Halo Loka Batik Pekanbaru, saya ingin tanya koleksi batik yang ready dan ukuran yang tersedia.',
  'Batik Riau kontemporer untuk kerja, acara resmi, dan hadiah berkelas.',
  'Demo ini menonjolkan lookbook, koleksi pilihan, rentang harga, ukuran, dan cerita motif agar produk terasa premium tanpa harus membangun toko online penuh.',
  'Chat Stylist',
  'Lihat Koleksi',
  'Lookbook koleksi baru',
  '/demo/loka-batik-pekanbaru.svg',
  'Katalog terasa seperti lookbook butik.',
  '[{"name": "Kemeja Motif Lancang", "price": "Rp289rb", "desc": "Potongan rapi untuk kerja dan agenda formal."}, {"name": "Outer Melayu Modern", "price": "Rp349rb", "desc": "Layer ringan dengan detail motif Riau yang tetap modern."}, {"name": "Couple Seri Siak", "price": "Rp625rb", "desc": "Paket pasangan untuk acara keluarga, kantor, dan undangan."}]',
  '["Kemeja batik pria", "Outer batik wanita", "Set couple acara resmi"]',
  '[{"value": "12+", "label": "koleksi aktif"}, {"value": "S-XXL", "label": "size tersedia"}, {"value": "2 hari", "label": "kirim Pekanbaru"}]',
  'Yang dijual bukan cuma kain, tapi rasa percaya diri.',
  '["Lookbook editorial untuk membuat koleksi terlihat premium.", "Size guide singkat supaya pembeli tidak ragu memilih ukuran.", "Cerita motif memberi alasan emosional untuk membeli."]',
  'Koleksi jadi kelihatan jauh lebih butik. Customer langsung tanya size, bukan lagi minta foto satu-satu.',
  'Rani, owner Loka Batik',
  'Jadikan katalog batik terasa seperti butik digital.',
  'Demo Landing Page Loka Batik Pekanbaru | PekanWeb Studio',
  'Contoh landing page satu halaman untuk brand batik Pekanbaru dengan katalog premium.'
),
(
  'bersihkilap-home-care',
  'BersihKilap Home Care',
  'Jasa home cleaning',
  'cleaning',
  '6282387025429',
  'Halo BersihKilap Home Care, saya ingin booking layanan cleaning dan tanya estimasi harga.',
  'Booking cleaning rumah jadi jelas: layanan, area, estimasi, dan jadwal dalam satu halaman.',
  'Demo ini dibuat untuk jasa profesional yang perlu membangun trust cepat: bukti before-after, daftar layanan, area kerja, checklist SOP, dan tombol booking WhatsApp.',
  'Booking Jadwal',
  'Cek Layanan',
  'Tim datang terjadwal',
  '/demo/bersihkilap-home-care.svg',
  'Layanan dibuat mudah dipilih sebelum chat.',
  '[{"name": "General Cleaning", "price": "Mulai Rp250rb", "desc": "Pembersihan rutin untuk rumah, kos, dan apartemen kecil."}, {"name": "Deep Cleaning", "price": "Mulai Rp550rb", "desc": "Pembersihan detail untuk dapur, kamar mandi, kaca, dan sudut sulit."}, {"name": "Sofa & Kasur", "price": "Mulai Rp180rb", "desc": "Vacuum ekstraksi untuk noda, debu, dan bau tidak sedap."}]',
  '["Deep cleaning rumah", "Cuci sofa & kasur", "Cleaning pasca renovasi"]',
  '[{"value": "4 layanan", "label": "rumah & kos"}, {"value": "SOP", "label": "alat higienis"}, {"value": "8 area", "label": "Pekanbaru"}]',
  'Trust datang dari detail yang terlihat.',
  '["Before-after besar agar hasil kerja cepat terbaca.", "Checklist SOP untuk menunjukkan proses profesional.", "Area layanan dan estimasi harga mengurangi chat berulang."]',
  'Calon customer langsung kirim foto ruangan dan pilih layanan. Admin tidak perlu menjelaskan dari nol terus.',
  'Dimas, koordinator lapangan',
  'Buat booking jasa rumah terasa rapi sejak klik pertama.',
  'Demo Landing Page BersihKilap Home Care | PekanWeb Studio',
  'Contoh landing page satu halaman untuk jasa home cleaning profesional di Pekanbaru.'
);